CREATE TABLE IF NOT EXISTS EQUIPMENTS_LIBRARY
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_name VARCHAR                                 NOT NULL,
    volume         INTEGER,
    orientation    VARCHAR,
    model          VARCHAR,
    CONSTRAINT pk_equipmentLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS_LIBRARY
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_name VARCHAR                                 NOT NULL,
    equipment_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_elementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_ELEMENTS_LIBRARY_ON_EQUIPMENTS_LIBRARY FOREIGN KEY (equipment_id) REFERENCES equipments_library (id)
);

CREATE TABLE IF NOT EXISTS PARTS_ELEMENT_LIBRARY
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_name  VARCHAR                                 NOT NULL,
    element_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_partElementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_PARTS_ELEMENT_LIBRARY_ON_ELEMENTS_LIBRARY FOREIGN KEY (element_id) REFERENCES elements_library (id)
);

CREATE TABLE IF NOT EXISTS STANDARD_SIZES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    standard_size_string VARCHAR                                 NOT NULL,
    thickness            DOUBLE PRECISION,
    min_diameter         INTEGER,
    min_thickness        DOUBLE PRECISION,
    max_diameter         INTEGER,
    max_thickness        DOUBLE PRECISION,
    CONSTRAINT pk_standardSize PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_DEVIATIONS_GEODESY
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id              BIGINT                                  NOT NULL,
    fulls                             BOOLEAN                                 NOT NULL,
    old                               BOOLEAN                                 NOT NULL,
    volume                            INTEGER                                 NOT NULL,
    acceptable_precipitation          INTEGER                                 NOT NULL,
    max_difference_neighboring_points INTEGER                                 NOT NULL,
    max_difference_diametric_points   INTEGER                                 NOT NULL,
    CONSTRAINT pk_permissibleDeviationsGeodesy PRIMARY KEY (id),
    CONSTRAINT UQ_PERMISSIBLE_DEVIATIONS_GEODESY UNIQUE (equipment_library_id, fulls, old)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_METAL_HARDNESS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id    BIGINT                                  NOT NULL,
    element_library_id      BIGINT                                  NOT NULL,
    part_element_library_id BIGINT,
    standard_size_string    VARCHAR                                 NOT NULL,
    min_diameter            INTEGER,
    min_thickness           DOUBLE PRECISION,
    min_hardness            INTEGER                                 NOT NULL,
    max_hardness            INTEGER,
    measurement_error       FLOAT,
    CONSTRAINT pk_acceptableMetalHardness PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_RESIDUAL_THICKNESS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id    BIGINT                                  NOT NULL,
    element_library_id      BIGINT                                  NOT NULL,
    part_element_library_id BIGINT,
    standard_size_string    VARCHAR                                 NOT NULL,
    min_diameter            INTEGER,
    min_thickness           DOUBLE PRECISION,
    max_diameter            INTEGER,
    max_thickness           DOUBLE PRECISION,
    acceptable_thickness    DOUBLE PRECISION,
    acceptable_percent      INTEGER,
    measurement_error       FLOAT,
    CONSTRAINT pk_acceptableResidualThickness PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DEFECTS_LIBRARY
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    defect_name             VARCHAR                                 NOT NULL,
    unacceptable            BOOLEAN                                 NOT NULL,
    use_calculate_thickness VARCHAR                                 NOT NULL,
    calculation             VARCHAR                                 NOT NULL,
    CONSTRAINT pk_defectLibrary PRIMARY KEY (id),
    CONSTRAINT UQ_DEFECTS_LIBRARY UNIQUE (defect_name)
);

CREATE TABLE IF NOT EXISTS REPAIRS_LIBRARY
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    repair_name VARCHAR                                 NOT NULL,
    calculation VARCHAR                                 NOT NULL,
    CONSTRAINT pk_repairLibrary PRIMARY KEY (id),
    CONSTRAINT UQ_REPAIRS_LIBRARY UNIQUE (repair_name)
);

CREATE TABLE IF NOT EXISTS LIBRARY_MEASUREMENT_PARAMETERS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parameter_name    VARCHAR                                 NOT NULL,
    max_allowed_value DOUBLE PRECISION,
    unit_measurement  VARCHAR                                 NOT NULL,
    defect_id         BIGINT,
    repair_id         BIGINT,
    CONSTRAINT pk_measurementParameterLibrary PRIMARY KEY (id),
    CONSTRAINT FK_LIBRARY_MEASUREMENT_PARAMETERS_ON_DEFECTS_LIBRARY
        FOREIGN KEY (defect_id) REFERENCES defects_library (id),
    CONSTRAINT FK_LIBRARY_MEASUREMENT_PARAMETERS_ON_REPAIRS_LIBRARY
        FOREIGN KEY (repair_id) REFERENCES repairs_library (id)
);