version: '3.8'
services:
  eureka-service:
    build: eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "http://eureka-service:8761/healthz" ]
      interval: 10s
      retries: 5
      timeout: 10s

  company-service:
    build: company-service
    container_name: company-service
    ports:
      - "8081:8081"
    depends_on:
     company-db:
       condition: service_started
     eureka-service:
       condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://company-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  company-db:
    image: postgres:14-alpine
    container_name: company-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  laboratory-qc-service:
    build: laboratory-qc-service
    container_name: laboratory-qc-service
    ports:
      - "8082:8082"
    depends_on:
      laboratory-qc-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      company-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://laboratory-qc-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  laboratory-qc-db:
    image: postgres:14-alpine
    container_name: laboratory-qc-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  equipment-service:
    build: equipment-service
    container_name: equipment-service
    ports:
      - "8083:8083"
    depends_on:
      equipment-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      laboratory-qc-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://equipment-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  equipment-db:
    image: postgres:14-alpine
    container_name: equipment-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  library-service:
    build: library-service
    container_name: library-service
    ports:
      - "8084:8084"
    depends_on:
      library-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      equipment-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  library-db:
    image: postgres:14-alpine
    container_name: library-db
    ports:
      - "6548:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  measurement-qc-service:
    build: measurement-qc-service
    container_name: measurement-qc-service
    ports:
      - "8085:8085"
    depends_on:
      measurement-qc-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      library-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://measurement-qc-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  measurement-qc-db:
    image: postgres:14-alpine
    container_name: measurement-qc-db
    ports:
      - "6550:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  document-qc-service:
    build: document-qc-service
    container_name: document-qc-service
    ports:
      - "8086:8086"
    depends_on:
      document-qc-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      measurement-qc-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-qc-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  document-qc-db:
    image: postgres:14-alpine
    container_name: document-qc-db
    ports:
      - "6552:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  document-template-service:
    build: document-template-service
    container_name: document-template-service
    ports:
      - "8087:8087"
    depends_on:
      document-template-db:
        condition: service_started
      eureka-service:
        condition: service_healthy
      document-qc-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-template-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  document-template-db:
    image: postgres:14-alpine
    container_name: document-template-db
    ports:
      - "6554:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords

  gateway-service:
    build: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
