springdoc:
  swagger-ui:
    path: /swagger-ui-measurement-qc-service.html

server:
  port: 8085

spring:
  application:
    name: measurement-qc-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username: postgres
      password: mywords

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true