CREATE TABLE IF NOT EXISTS COMPLETED_REPAIR_MEASUREMENTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id      BIGINT                                  NOT NULL,
    repair_id         BIGINT                                  NOT NULL,
    repair_name       VARCHAR                                 NOT NULL,
    element_id        BIGINT                                  NOT NULL,
    element_name      VARCHAR                                 NOT NULL,
    part_element_id   BIGINT,
    part_element_name VARCHAR,
    CONSTRAINT pk_completedRepairMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GEODESIC_MEASUREMENTS
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id                BIGINT                                  NOT NULL,
    measurement_number          INTEGER                                 NOT NULL,
    sequential_number           INTEGER                                 NOT NULL,
    number_measurement_location INTEGER                                 NOT NULL,
    reference_point_value       INTEGER,
    control_point_value         INTEGER                                 NOT NULL,
    transition_value            INTEGER,
    CONSTRAINT pk_geodesicMeasurements PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HARDNESS_MEASUREMENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_date   DATE                                    NOT NULL,
    equipment_id       BIGINT                                  NOT NULL,
    element_id         BIGINT                                  NOT NULL,
    element_name       VARCHAR                                 NOT NULL,
    part_element_id    BIGINT,
    part_element_name  VARCHAR,
    measurement_number INTEGER,
    standard_size      VARCHAR                                 NOT NULL,
    measurement_value  DOUBLE PRECISION                        NOT NULL,
    status             VARCHAR                                 NOT NULL,
    measurement_status VARCHAR                                 NOT NULL,
    acceptable         BOOLEAN,
    invalid            BOOLEAN,
    no_standard        BOOLEAN,
    CONSTRAINT pk_hardnessMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS IDENTIFIED_DEFECT_MEASUREMENTS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id            BIGINT                                  NOT NULL,
    element_name            VARCHAR                                 NOT NULL,
    part_element_name       VARCHAR,
    defect_id               BIGINT                                  NOT NULL,
    defect_name             VARCHAR                                 NOT NULL,
    unacceptable            BOOLEAN,
    quality_assessment      VARCHAR,
    use_calculate_thickness BOOLEAN                                 NOT NULL,
    element_id              BIGINT                                  NOT NULL,
    part_element_id         BIGINT,
    CONSTRAINT pk_identifiedDefectMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ULTRASONIC_MEASUREMENTS
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_date      DATE                                    NOT NULL,
    equipment_id          BIGINT                                  NOT NULL,
    element_id            BIGINT                                  NOT NULL,
    element_name          VARCHAR                                 NOT NULL,
    part_element_id       BIGINT,
    part_element_name     VARCHAR,
    standard_size         VARCHAR                                 NOT NULL,
    measurement_number    INTEGER,
    min_measurement_value DOUBLE PRECISION                        NOT NULL,
    max_measurement_value DOUBLE PRECISION                        NOT NULL,
    max_corrosion         DOUBLE PRECISION,
    residual_thickness    DOUBLE PRECISION                        NOT NULL,
    min_acceptable_value  DOUBLE PRECISION,
    measurement_status    VARCHAR                                 NOT NULL,
    status                VARCHAR                                 NOT NULL,
    CONSTRAINT pk_ultrasonicResidualThicknessMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS VISUAL_MEASUREMENT_CONTROL
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_journal_id     BIGINT                                  NOT NULL,
    welded_joint_number VARCHAR                                 NOT NULL,
    standard_size       VARCHAR                                 NOT NULL,
    defect_name         VARCHAR                                 NOT NULL,
    coordinates         VARCHAR                                 NOT NULL,
    quality_assessment  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_visualMeasurementControl PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ULTRASONIC_CONTROL
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_journal_id     BIGINT                                  NOT NULL,
    welded_joint_number VARCHAR                                 NOT NULL,
    standard_size       VARCHAR                                 NOT NULL,
    description_defect  VARCHAR                                 NOT NULL,
    coordinates         VARCHAR                                 NOT NULL,
    quality_assessment  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_ultrasonicControl PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS MEASURED_PARAMETERS
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parameter_id     BIGINT                                  NOT NULL,
    parameter_name   VARCHAR                                 NOT NULL,
    value            DOUBLE PRECISION                        NOT NULL,
    unit_measurement VARCHAR                                 NOT NULL,
    defect_id        BIGINT,
    repair_id        BIGINT,
    vm_control_id    BIGINT,
    CONSTRAINT pk_measuredParameter PRIMARY KEY (id),
    CONSTRAINT FK_MEASURED_PARAMETERS_ON_IDENTIFIED_DEFECT_MEASUREMENTS FOREIGN KEY (defect_id)
        REFERENCES identified_defect_measurements (id),
    CONSTRAINT FK_MEASURED_PARAMETERS_ON_COMPLETED_REPAIR_MEASUREMENTS FOREIGN KEY (repair_id)
        REFERENCES completed_repair_measurements (id),
    CONSTRAINT FK_MEASURED_PARAMETERS_ON_VISUAL_MEASURING_CONTROLS
        FOREIGN KEY (vm_control_id) REFERENCES visual_measurement_control (id)
);