CREATE TABLE IF NOT EXISTS EQUIPMENTS_LIBRARY
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_name VARCHAR                                 NOT NULL,
    volume         INTEGER,
    orientation    VARCHAR,
    model          VARCHAR,
    CONSTRAINT pk_equipmentLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS_LIBRARY
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_name VARCHAR                                 NOT NULL,
    equipment_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_elementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_ELEMENTS_LIBRARY_ON_EQUIPMENTS_LIBRARY FOREIGN KEY (equipment_id) REFERENCES equipments_library (id)
);

CREATE TABLE IF NOT EXISTS PARTS_ELEMENT_LIBRARY
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_name  VARCHAR                                 NOT NULL,
    element_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_partElementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_PARTS_ELEMENT_LIBRARY_ON_ELEMENTS_LIBRARY FOREIGN KEY (element_id) REFERENCES elements_library (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENTS
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id BIGINT                                  NOT NULL,
    building_id          BIGINT                                  NOT NULL,
    equipment_name       VARCHAR                                 NOT NULL,
    stationary_number    INTEGER,
    geodesy_locations    INTEGER,
    model                VARCHAR,
    room                 VARCHAR,
    volume               INTEGER,
    old                  BOOLEAN,
    CONSTRAINT pk_equipment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_ELEMENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_library_id BIGINT                                  NOT NULL,
    element_name       VARCHAR                                 NOT NULL,
    standard_size      VARCHAR,
    equipment_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipmentElement PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENT_ELEMENTS_ON_EQUIPMENT_DIAGNOSED
        FOREIGN KEY (equipment_id) REFERENCES equipments (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_PARTS_ELEMENTS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_element_library_id BIGINT                                  NOT NULL,
    part_element_name       VARCHAR                                 NOT NULL,
    standard_size           VARCHAR                                 NOT NULL,
    element_id              BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipmentPartElement PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENT_PARTS_ELEMENTS_ON_EQUIPMENT_ELEMENTS
        FOREIGN KEY (element_id) REFERENCES equipment_elements (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_PASSPORT
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id      BIGINT                                  NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    header            VARCHAR                                 NOT NULL,
    meaning           VARCHAR                                 NOT NULL,
    use_to_protocol   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_equipmentPassport PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_INSPECTIONS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id    BIGINT                                  NOT NULL,
    date            VARCHAR                                 NOT NULL,
    inspection      VARCHAR                                 NOT NULL,
    document_number VARCHAR                                 NOT NULL,
    organization    VARCHAR                                 NOT NULL,
    CONSTRAINT pk_equipmentInspection PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_REPAIRS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id BIGINT                                  NOT NULL,
    date         VARCHAR                                 NOT NULL,
    description  VARCHAR                                 NOT NULL,
    organization VARCHAR,
    CONSTRAINT pk_equipmentRepair PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REMARKS_SPECIALISTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id      BIGINT                                  NOT NULL,
    element_id        BIGINT                                  NOT NULL,
    element_name      VARCHAR                                 NOT NULL,
    part_element_id   BIGINT,
    part_element_name VARCHAR,
    remark            VARCHAR                                 NOT NULL,
    CONSTRAINT pk_remarkSpecialist PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_SPECIALISTS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id   BIGINT                                  NOT NULL,
    recommendation VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendationSpecialist PRIMARY KEY (id)
);